# Network 명시적 정의
networks:
  short4-network:
    driver: bridge

# 서비스 정의
services:
  # MongoDB 컨테이너
  mongodb:
    image: 'mongo:latest'
    command: mongod --auth
    secrets:
      - mongodb_root_password
      - mongodb_user_password
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - ./volume/mongo/db:/data/db
      - ./volume/mongo/configdb:/data/configdb
    networks:
      - short4-network
    expose:
      - '27017'
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: java -jar /app/server.jar
    secrets:
      - mongodb_user_password
    depends_on:
      - mongodb
    networks:
      - short4-network
    ports:
      - '8080:8080'

# 인증정보 정의
secrets:
  mongodb_root_password:
    file: ./secret/mongodb_root_password.secret.txt
  mongodb_user_password:
    file: ./secret/mongodb_user_password.secret.txt