####################################
###   Development 환경 compose    ###
####################################

# Network 명시적 정의
networks:
  short4-network-dev:
    driver: bridge

# 서비스 정의
services:
  # MongoDB 컨테이너
  mongodb-dev:
    container_name: mongodb-dev-container
    image: 'mongo:latest'
    command: mongod --bind_ip_all
    volumes:
      - ../script/dev.init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - ../volume/dev/mongo/db:/data/db
      - ../volume/dev/mongo/configdb:/data/configdb
    networks:
      - short4-network-dev
    ports:
      - '28000:27017'